### ISSUE TITLE
Conflict with Apache?

### ISSUE THREAD

**Issue by raphaelbastide** [new-computers/seeder#15]
The address outputted by the install script seams to be in conflict with Apache: When I open `http://raspberrypi.local`, I see the content of `/home/pi/www` or any app installed there. Is it something I can avoid?

**Comment by kodedninja** [comment]
That's because sometimes Apache has port `80` by default. 

You can fix it by `sudo systemctl disable apache2` or by removing Apache fully.

**Comment by raphaelbastide** [comment]
I fixed it by removing Apache. Thank you @kodedninja!

**Comment by kodedninja** [comment]
No problem @raphaelbastide! Thanks for the feedback.
