### ISSUE TITLE
Script URL

### ISSUE THREAD

**Issue by raphaelbastide** [new-computers/seeder#16]
With my configuration, 
```
curl -o- https://git.io/vxpck | bash
```
downloads nothing, while
```
curl -o- https://raw.githubusercontent.com/new-computers/seeder/master/install.sh | bash
```
does. Not sure you can reproduce this error, can you?

Also, it may be useful to add to the documentation that `~/seeder` must be writeable.

**Comment by kodedninja** [comment]
Hmm this is weird, the link works perfectly for me.

Wasn't it just a temporary error?

**Comment by raphaelbastide** [comment]
No it wasn’t temporary. I tested it on 2 rpi and same result as well on my Linux laptop.

**Comment by kodedninja** [comment]
It may be a firewall issue or I don't know :disappointed: I will add `curl -o- https://raw.githubusercontent.com/new-computers/seeder/master/install.sh | bash` to the documentation as an alternative.

I think the directory becomes unwritable when you sudo install it. What do you think should be added to the doc? Or in what form?

**Comment by raphaelbastide** [comment]
> I think the directory becomes unwritable when you sudo install it. What do you think should be added to the doc? Or in what form?

Maybe to add `chmod 777 -R ~/seeder`? This is what I had to do to avoid an infinite error prompt due to the access of this directory. But again, I wonder what is specific to my setups or generic. Maybe extra tests needs to be done to confirm my issues :)
