### ISSUE TITLE
Installing on non-raspberry pi computers

### ISSUE THREAD

**Issue by tmcw** [new-computers/seeder#17]
![img_5324-resize](https://user-images.githubusercontent.com/32314/39281807-61a758f6-48bb-11e8-9801-9e1033c24fa7.jpg)

🙏 it works! Thanks to all involved with this project, it's _exactly_ what I was looking for. I just got it up and running on my hardware - a Lenovo x220i. The process was essentially

- Read what install.sh does
- Everywhere that install.sh refers to `/pi/`, replace that with the current username

Besides that, everything about this should work on any hardware, so - and maybe this is scope-creep - where it currently hardcodes pi, it could use `whoami` or support some sort of which-user configuration?

**Comment by kodedninja** [comment]
Thanks for the feedback! I know the hardcoded pi thing is very frustrating and will try to come up with something.

The problem is that it uses `systemctl`and the the root directory is different then.

**Comment by callil** [comment]
@tmcw wow this pic makes me so happy!
