### ISSUE TITLE
Issue running install.sh on latest Raspbian

### ISSUE THREAD

**Issue by louiscenter** [new-computers/seeder#18]
Hey all, got this working, it's fantastic! https://twitter.com/louiscenter/status/989606594697625606

![seeder](https://user-images.githubusercontent.com/17946150/39356978-b81ec24e-4a11-11e8-8809-aca07a491510.jpg)

I am running this on a Model B, with a fresh install of Raspbian via NOOBS. That said, I still had one issue running`install.sh`:

The latest version of Raspbian appears to have `node v4` installed, so when `install.sh` checks to see if `node` exists, it will skip installing `nvm`. The issue here is that, for whatever reason, Raspbian includes `node`, but not `npm`, so the rest of the script will fail to execute correctly. Maybe the check would need to be updated to see if both `node` *and* `npm` exist, before skipping over `nvm` installation.

**Comment by kodedninja** [comment]
Hey, please check if node and npm are installed for sudo too. I've got the same problem.

So basically `sudo npm install` wasn't working.
