### ISSUE TITLE
./install.sh fails on device - permission errors

### ISSUE THREAD

**Issue by callil** [new-computers/seeder#3]
right now I'm getting permission errors when running the install script. If I manually `sudo npm install` things seem to work fine.

**Comment by kodedninja** [comment]
I want to rewrite the whole install script with one that does everything automatically. Downloads the project and sets up paths and all that. Also installs node if it's needed.

Will start a new issue on that.

**Comment by kodedninja** [comment]
By the way, this can be fixed with `chmod +x install.sh`.
